image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install
  - apt-get update -y
  - apt-get install -y build-essential curl
  - curl -sL https://deb.nodesource.com/setup_8.x | bash
  - source /root/.bashrc 
  - apt-get install -y nodejs
  - npm install -g yarn

develop:
  stage: test
  script:
  - yarn install 
  - npm run build
  - bundle exec jekyll build -d public/$CI_COMMIT_REF_NAME
  artifacts:
    paths:
    - $CI_COMMIT_REF_NAME
  except:
  - master

pages:
  stage: deploy
  script:
  - yarn install 
  - npm run build
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
