image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install
  - apt-get update -y
  - apt-get install -y build-essential curl
  - curl -sL https://deb.nodesource.com/setup_8.x | bash
  - source /root/.bashrc 
  - apt-get install -y nodejs gcc g++ make.
  - npm install -g yarn
  - npm run gulp

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
