# Site settings
title: Breathub
email: info@breathub.com
description: Breathub
logo: "/assets/img/breathub/breathub-logo-trimmed.png"

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://breathub.com" # the base hostname & protocol for your site

# Site Contents

header:
  nav: headernav
  description: "Her türlü outdoor aktivitesi ve lokasyonları hakkında kapsamlı bilgi edinin, Outdoor Aktivite Sağlayıcıları ile online ve güvenilir alışveriş yapın."
  screenPath: "/assets/img/breathub/breathub-demo-screen.png"

download:
  nav: downloadnav
  header:
  description:

services:
  nav: servicesnav
  header: "Outdoor Aktivitelerine dair Herşeyi Bulabilirsin"
  subheader: "Yaşadığını hissetmeye hazır mısın?"
  screenPath: "/assets/img/breathub/breathub-demo-screen-services.png"
  serviceList:
    - icon: icon-map
      header: Lokasyon
      content: Outdoor aktivite yapılabilecek alanların ve rotaların, online ve offline datalar ile sunulması.
    - icon: icon-basket-loaded
      header: Outdoor Aktivite Sağlayıcıları
      content: Outdoor aktivite sağlayıcıları, kursları ve mekanlarının bulunduğu bir pazaryeri.
    - icon: icon-user
      header: Kişiselleştirme
      content: Kişisel ilgi alanlarına göre içerikler, kampanyalar, tavsiyeler, keşif araçları ve topluluklar.
    - icon: icon-credit-card
      header: Online Ödeme ve Rezervasyon
      content: Kampanyalar, ve Eşsiz Fiyatlar

portfolio:
  nav: portfolionav
  header: "İster huzurun, ister maceranın, ister adrenalinin tadını çıkar"
  subheader: ""
  portfolioList:
    - title: Tüm bunlar hakkında bilgiler, online ödeme ve harita üzerinde lokasyon bilgisi 
      category: Plajlar, Koylar ve Beach club'lar
      imgPath: /assets/img/portfolio/1.jpg
      link: \#
    - title: Deneyimler ve Yorumlar, Profesyonel içerikler tavsiyeler ve öneriler, Ekosistem bilgileri 
      category: Kamp alanlari
      imgPath: /assets/img/portfolio/2.jpg
      link: \#
    - title:  Rotalar, Tavsiyeler, Zorluk dereclerine göre sınıflandırma, Profesyonel İçerikler
      category:  Dağcılık
      imgPath: /assets/img/portfolio/3.jpg
      link: \#
    - title: Balık tutmaya elverişli noktalar, tiyolar, Profesyonel içerikler
      category: Balıkçılık 
      imgPath: /assets/img/portfolio/4.jpg
      link: \#
    - title: Dalış Merkezleri Karşılaştırma, Dalış merkezi hakkında her türlü bilgi, Online ödeme ve rezervasyon seçeneği
      category: Tüplü Dalış
      imgPath: /assets/img/portfolio/5.jpg
      link: \#
    - title: Yüzlerce Outdoor Aktivitesi seni bekliyor.
      category: Ve daha niceleri...
      imgPath: /assets/img/portfolio/6.png
      link: \#

feature:
  nav: featurenav
  header: İşletmenizi (breathub-logo) ile büyütün.
  featureList:
    - icon: fa-accusoft
      header: İşletme Yönetim Paneli
      description: Breathub işletme hedeflerinizi, nakit akışlarınızı, toplam müşteri sayılarınızı takip edebileceğiniz kullanışlı ve basit analiz araçları sunar. 
    - icon: fa-child
      header: Müşteri Yönetimi
      description: Müşterilerinizin online rezervasyonlarını ve ödemelerini takip edip onlarla iletişime geçebilirsiniz.Müşterileriniz hakkında analiz raporları alıp kampanyalarınızı ve stratejilerinizi belirleyebilirsiniz.
    - icon: fa-credit-card
      header: Online Ödeme Alma
      description: Çeşitli ödeme yöntemlerini kabul etmeye başlayın. Daimi ve günlük müşterilerinize kredi ve banka kartı ile ödeme imkanı sunun.
    - icon: fa-adversal
      header: Platform İçi Kampanyalar ve Reklamlar
      description: breathub içerisinde yer alan potansiyel müşterilerinize özel kampanyalar ve reklamlar düzenleyin.

aside:
  nav: asidenav
  header: breathub seninle, her yerde.
  subheader: ""

contact:
  nav: contactnav
  header: Bize Ulaşın!
  description: Dilek ve şikayetlerinizi burada belirtebilirsiniz.
  FS:
    mail: info@breathub.com #Formspree'nin gonderdigi mail adresi.
    nameLabel: Isim-Soyisim
    mailLabel: Mail Adresiniz
    messageLabel: Mesajiniz
    submitLabel: Gönder


#Google Ad Words Data from scripts code (using Google responsive options) and ad client
# data-ad-slot: 2973388149
# data-ad-client: ca-pub-9204963049240271
# google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-86331249-1"
addthis_id: ra-5644da281510c62f
disqus_account: jeky-new-age

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/lantoniotrento
  - title: facebook
    url: https://facebook.com/lantoniotrento
  - title: google-plus
    url: https://plus.google.com/+AntoniotrentoIt
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: 
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag]
# Build settings
